version: '3.8'

services:
  postgres:
    image: 'postgres:14.2'
    container_name: 'career-postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'career'
      POSTGRES_PASSWORD: 'career!'
      POSTGRES_DB: 'career'
    volumes:
      - career-postgres-data:/var/lib/postgresql/data

  back:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - '7070:7070'

  ai:
    build:
      context: ./packages/models
      dockerfile: Dockerfile
    ports:
      - '8501:8501'
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  career-postgres-data:
    external: true
