version: '3.8'

services:
  postgres:
    image: 'postgres:14.2'
    container_name: 'career-postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'career'
      POSTGRES_PASSWORD: 'career!'
      POSTGRES_DB: 'career'
    volumes:
      - career-postgres-data:/var/lib/postgresql/data

  back:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - 10.128.0.2:8000:8000

  ai:
    build:
      context: ./packages/ai
      dockerfile: Dockerfile
    ports:
      - '8887:8887'
    volumes:
      - ./packages/ai:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8887']
      interval: 30s
      retries: 3

volumes:
  career-postgres-data:
    external: true
