services:
  postgres:
    image: 'postgres:14.2'
    container_name: 'career-postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'career'
      POSTGRES_PASSWORD: 'career!'
      POSTGRES_DB: 'career'
    volumes:
      - career-postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  back:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

  ai:
    build:
      context: ./packages/ai
      dockerfile: Dockerfile
    ports:
      - '8887:8887'
    volumes:
      - ./packages/ai:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8887']
      interval: 30s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  nginx_prod:
    container_name: 'nginx_prod'
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  career-postgres-data:
    external: true
