export * from './user.entity.js';
export * from './university.entity.js';
export * from './partner.entity.js';
export * from './educational-centers.entity.js';
export * from './articles.entity.js';
export * from './specialty.entity.js';
export * from './test.entity.js';
export * from './courses.entity.js';
export * from './lessons.entity.js';
