export * from './user.service.js';
export * from './university.service.js';
export * from './image-storage.service.js';
export * from './partner.service.js';
export * from './articles.service.js';
export * from './educational-centers.service.js';
export * from './specialty.service.js';
export * from './test.service.js';
export * from './courses.service.js';
