export * from './university.swagger.js';
export * from './user.swagger.js';
export * from './image.swagger.js';
export * from './partner.swagger.js';
export * from './articles.swagger.js';
export * from './specialty.swagger.js';
export * from './test.swagger.js';
export * from './educational-centers.swagger.js';
export * from './courses.swagger.js';
