export * from './user.repository.js';
export * from './university.repository.js';
export * from './partner.repository.js';
export * from './educational-centers.repository.js';
export * from './articles.repository.js';
export * from './specialty.repository.js';
export * from './test.repository.js';
export * from './courses.repository.js';
export * from './lessons.repository.js';
