version: '3.8'

volumes:
  career-postgres-data:
    external: true

services:
  postgres:
    image: 'postgres:14.2'
    container_name: 'career-postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'career'
      POSTGRES_PASSWORD: 'career!'
      POSTGRES_DB: 'career'
    volumes:
      - career-postgres-data:/var/lib/postgresql/data

  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-server
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres

  #   volumes:
  #     - ./src:/app/src
